version: "3.8"
services:
  web:
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
      - neo4j

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  neo4j:
    image: neo4j:5
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      NEO4J_AUTH: "${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-password}"
      NEO4J_PLUGINS: '["apoc"]'
      NEO4JLABS_PLUGINS: '["apoc"]'
    volumes:
      - neo4j_data:/data

volumes:
  mongo_data:
  redis_data:
  neo4j_data:
